stages:
  - test
  - coverage

variables:
  APP_ENV: "testing"

.before_template: &before_script
  before_script:
    - composer global require hirak/prestissimo
    - composer install --prefer-dist --no-interaction --no-progress
.standard_template: &standard_deploy
  services:
    - mysql:latest
  artifacts:
      when: on_failure
      expire_in: 1 day
      paths:
          - storage/logs/laravel.log
  variables:
    DB_HOST: mysql
    DB_USERNAME: root
    DB_PASSWORD: root
    DB_DATABASE: testing
    MYSQL_DATABASE: testing
    MYSQL_ROOT_PASSWORD: root
  stage: test
  script:
    - bash tests/scripts/setup.sh
    - vendor/bin/phpunit -d memory_limit=512M --coverage-text --colors=never

test-7.1:
  image: nothinghere/php-7.1:latest
  <<: *before_script
  <<: *standard_deploy

code-coverage:
  image: nothinghere/php-7.1:latest
  <<: *before_script
  stage: coverage
  when: on_success
  script:
    - bash tests/scripts/setup.sh
    - vendor/bin/phpunit -d memory_limit=1G --coverage=text --colors=never --testsuite=NonExisting
