image: php:7.1

stages:
  - test
  - coverage
  
cache:
  paths:
    - vendor/
  
.mariadb_template: &mariadb
    services:
        - mariadb:latest
    variables:
        DB_HOST: mariadb
        DB_CONNECTION: mysql
        TENANCY_SYSTEM_CONNECTION_NAME: mysql
        MYSQL_DATABASE: testing
        MYSQL_ROOT_PASSWORD: root
        
.pgsql_template: &pgsql
    services:
        - postgres:latest
    variables:
        DB_HOST: postgres
        DB_CONNECTION: pgsql
        TENANCY_SYSTEM_CONNECTION_NAME: pgsql
        POSTGRES_DB: testing
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root

.before_template: &before_script
  before_script:
    - apt-get -yqq update
    - apt-get -qqy install git unzip zip libpq-dev
    - docker-php-ext-install pdo_pgsql pdo_mysql
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar composer
    - php composer global require hirak/prestissimo

.standard_template: &standard_deploy
  cache:
    key: "$CI_JOB_NAME"
    untracked: false
  artifacts:
      when: on_failure
      expire_in: 8 hours
      paths:
          - vendor/laravel/laravel/storage/logs/laravel.log
  stage: test

test-7.1-L-5.3-pgsql:
  <<: *before_script
  <<: *standard_deploy
  <<: *pgsql
  script:
    - php tests/scripts/setup.php
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml
    
test-7.1-L-5.4-pgsql:
  <<: *before_script
  <<: *standard_deploy
  <<: *pgsql
  script:
    - php tests/scripts/setup.php
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml

test-7.1-L-5.3-mariadb:
  <<: *before_script
  <<: *standard_deploy
  <<: *mariadb
  script:
    - php tests/scripts/setup.php
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml

test-7.1-L-5.4-mariadb:
  <<: *before_script
  <<: *standard_deploy
  <<: *mariadb
  script:
    - php tests/scripts/setup.php
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml

test-7.1-L-master-mariadb:
  <<: *before_script
  <<: *standard_deploy
  <<: *mariadb
  allow_failure: true
  script:
    - php tests/scripts/setup.php
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml

code-coverage:
  <<: *before_script
  <<: *standard_deploy
  <<: *mariadb
  stage: coverage
  when: on_success
  script:
    - php composer install --prefer-dist -n
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - vendor/bin/phpunit -d memory_limit=1G --coverage-clover=coverage.xml -c ci.phpunit.xml
    - bash <(curl -s https://codecov.io/bash)
