image: php:7.1

stages:
  - test
  - coverage
  
cache:
  paths:
    - vendor/
  
variables:
  APP_ENV: "testing"
  QUEUE_DRIVER: "sync"

.before_template: &before_script
  before_script:
    - apt-get -yqq update
    - apt-get -qqy install git unzip zip
    - docker-php-ext-install pdo_mysql
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar composer
    - php composer global require hirak/prestissimo

.standard_template: &standard_deploy
  cache:
    key: "$CI_JOB_NAME"
    untracked: false
  services:
    - mysql:latest
  artifacts:
      when: on_failure
      expire_in: 8 hours
      paths:
          - vendor/laravel/laravel/storage/logs/laravel.log
  variables:
    DB_HOST: mysql
    DB_CONNECTION: mysql
    DB_USERNAME: root
    DB_PASSWORD: root
    DB_DATABASE: testing
    MYSQL_DATABASE: testing
    MYSQL_ROOT_PASSWORD: root
    TENANCY_SYSTEM_CONNECTION_NAME: mysql
    TENANCY_DEFAULT_HOSTNAME: local.testing
    APP_KEY: Phei9thoong3ai8aqu4ieHie6kee1zee
    QUEUE_DRIVER: sync
  stage: test

test-7.1-L-5.3:
  <<: *before_script
  <<: *standard_deploy
  script:
    - php composer update laravel/laravel:5.3 --dev --prefer-dist -n
    - bash tests/scripts/setup.sh
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml

test-7.1-L-5.4:
  <<: *before_script
  <<: *standard_deploy
  script:
    - php composer update laravel/laravel:5.4 --dev --prefer-dist -n
    - bash tests/scripts/setup.sh
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml

test-7.1-L-master:
  <<: *before_script
  <<: *standard_deploy
  allow_failure: true
  script:
    - php composer update laravel/laravel:dev-master --dev --prefer-dist -n
    - bash tests/scripts/setup.sh
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml

code-coverage:
  <<: *before_script
  <<: *standard_deploy
  stage: coverage
  when: on_success
  script:
    - php composer install --prefer-dist -n
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - vendor/bin/phpunit -d memory_limit=1G --coverage-clover=coverage.xml -c ci.phpunit.xml
    - bash <(curl -s https://codecov.io/bash)
