image: nothinghere/php-7.1:latest

stages:
  - test
  - coverage

variables:
  APP_ENV: "testing"
  QUEUE_DRIVER: "sync"

.before_template: &before_script
  before_script:
    - composer global require hirak/prestissimo
    - composer install --prefer-dist --no-interaction --no-progress

.standard_template: &standard_deploy
  services:
    - mysql:latest
  artifacts:
      when: on_failure
      expire_in: 8 hours
      paths:
          - vendor/laravel/laravel/storage/logs/laravel.log
  variables:
    DB_HOST: mysql
    DB_CONNECTION: mysql
    DB_USERNAME: root
    DB_PASSWORD: root
    DB_DATABASE: testing
    MYSQL_DATABASE: testing
    MYSQL_ROOT_PASSWORD: root
    TENANCY_SYSTEM_CONNECTION_NAME: mysql
  stage: test

test-7.1-L-5.3:
  <<: *before_script
  <<: *standard_deploy
  script:
    - composer require laravel/laravel:5.3
    - bash tests/scripts/setup.sh
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml

test-7.1-L-5.4:
  <<: *before_script
  <<: *standard_deploy
  script:
    - composer require laravel/laravel:5.4
    - bash tests/scripts/setup.sh
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml

test-7.1-L-master:
  <<: *before_script
  <<: *standard_deploy
  allow_failure: true
  script:
    - composer require laravel/laravel:dev-master
    - bash tests/scripts/setup.sh
    - vendor/bin/phpunit -d memory_limit=512M --colors=never -c ci.phpunit.xml

code-coverage:
  <<: *before_script
  stage: coverage
  when: on_success
  script:
    - pecl install xdebug
    - vendor/bin/phpunit -d memory_limit=1G --coverage-text --colors=never --testsuite=NonExisting -c ci.phpunit.xml
